services:
  modmail:
    build: .
    container_name: modmail
    volumes:
      - .:/data
    entrypoint: ["python", "bot.py"]
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '300M'
    restart: unless-stopped
